chkobba: main.cpp LOBBY/LobbyView.cpp GAME/GameView.cpp
	g++ -std=c++17 main.cpp LOBBY/LobbyView.cpp GAME/GameView.cpp \
	-I/opt/sfml2/include -L/opt/sfml2/lib \
	-lsfml-graphics -lsfml-window -lsfml-system -lsfml-network \
	-o chkobba